/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String hello() {
        return "Hello World!";
    }

    public String owner() {
        return "jeteish";
    }

    public static void main(String[] args) {
        System.out.println(new App().hello());
        System.out.println(new App().owner());
    }
}
