/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertEquals("Hello World!", classUnderTest.hello());
    }

    @Test
    public void appHasAnOwner() {
        App classUnderTest = new App();
        assertEquals("jeteish", classUnderTest.owner());
    }
}
